%[text] # Quaternion exponential map for a constant angular velocity
%[text] Computes the 4x4 quaternion multiplication matrix representing the exponential map exp(0.5*dt*Omega(w)), i.e. the incremental rotation quaternion generated by rotating at angular velocity `w` for time `dt`.
%[text] ## inputs
%[text] `scalar`: specifies the quaternion convention (passed to qMultMat)
%[text] `scalar == 0`: q = [cos(theta/2), e^T sin(theta/2)]^T (scalar-first)
%[text] `scalar == 4`: q = [e^T sin(theta/2), cos(theta/2)]^T (scalar-last)
%[text] `dt`: time step
%[text] `w`: angular velocity vector (3x1)
%[text] ## outputs
%[text] `qMat`: 4x4 quaternion multiplication matrix
%[text] ## note
%[text] NA
%[text] ## references
%[text] to be added
%[text] See also qMultMat.
function qMat = qExp(scalar, dt, w)
arguments (Input)
    scalar
    dt
    w
end

arguments (Output)
    qMat
end

w = w(:);
wNorm = norm(w);
qMat = eye(4,4) .* cos(0.5 * dt * wNorm) + qMultMat(scalar, 1, [w', 0]) ./ wNorm .* sin(0.5 * dt * wNorm);


end

%[appendix]{"version":"1.0"}
%---
